version: "3.9"
services:
  # client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`client-trackmiles.ovh001.eynes.com.ar`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=le"
    networks:
      - "traefik"

  # server
  server:
    build: ./server
    env_file:
      - ./server/.env.dev
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend-trackmiles.ovh001.eynes.com.ar`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
    depends_on:
    - db
    - redis
    - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "true"
    stdin_open: true
    tty: true
    networks:
      - "traefik"
 # database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - "traefik"

  # proxy
  #  proxy:
  #    image: nginx
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./data/nginx:/etc/nginx/conf.d
  #      # - ./data/www:/var/www/
  #      # - ./data/certbot/conf:/etc/letsencrypt
  #      # - ./data/certbot/www:/var/www/certbot
  #    links:
  #      - server
  #      - client
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # SSL certs
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # debugger
  celery:
    build: ./server
    command: "celery -A server worker -l INFO -E"

    depends_on:
      - server
    env_file:
      - ./server/.env.dev

  celery-beats:
    build: ./server
    command: "celery -A server beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - server
      - celery
    env_file:
      - ./server/.env.dev


  flower:
    build: ./server
    command: "celery -A server flower --address=0.0.0.0 --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - celery

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  wdb:
    image: kozea/wdb
    ports:
      - 1984:1984
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true

volumes:
  postgres_data:

networks:
  traefik:
    external: true
