version: "3.9"
services:
  fetcher:
    build: ./fetcher
    volumes:
      - ./fetcher:/app

  # client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app/
  # server
  server:
    build: ./server
    env_file:
      - ./server/.env.dev
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/app/
    depends_on:
    - db
    - redis
    - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "true"
    stdin_open: true
    tty: true
 # database
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  # proxy
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      # - ./data/www:/var/www/
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    links:
      - server
      - client
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # SSL certs
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # debugger
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  wdb:
    image: kozea/wdb
    ports:
      - 1984:1984
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true


volumes:
  postgres_data:
