version: "3.9"
services:
  # client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`client-trackmiles.ovh001.eynes.com.ar`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=le"
    networks:
      - "traefik"

  # server
  server:
    build: ./server
    env_file:
      - ./server/.env.dev
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend-trackmiles.ovh001.eynes.com.ar`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
    depends_on:
    - db
    - redis
    - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "true"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@admin.com"
      DJANGO_SUPERUSER_PASSWORD: "admin"
    stdin_open: true
    tty: true
    networks:
      - "traefik"
 # database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - "traefik"

  # debugger
  celery:
    build: ./server
    command: "celery -A server worker -l INFO -E"

    depends_on:
      - server
    env_file:
      - ./server/.env.dev

  celery-beats:
    build: ./server
    command: "celery -A server beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - server
      - celery
    env_file:
      - ./server/.env.dev
    networks:
      - "traefik"


  flower:
    build: ./server
    command: "celery -A server flower --address=0.0.0.0 --port=5555"
    # ports:
    #   - "5555:5555"
    depends_on:
      - celery
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower-trackmiles.ovh001.eynes.com.ar`)"
      - "traefik.http.routers.flower.entrypoints=websecure"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
      - "traefik.http.routers.flower.tls=true"
      - "traefik.http.routers.flower.tls.certresolver=le"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  wdb:
    image: kozea/wdb
    ports:
      - 1984:1984
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true

volumes:
  postgres_data:

networks:
  traefik:
    external: true
