# Generated by Django 4.1.4 on 2023-02-23 02:46

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptions',
            name='due',
            field=models.DateField(default=flights.models.Suscriptions.default_due_date),
        ),
    ]
