# Generated by Django 4.1.4 on 2023-02-17 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptions',
            name='due',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 0, 56, 39, 946818)),
        ),
    ]
