# Generated by Django 4.1.4 on 2023-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_suscriptions_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
