# Generated by Django 4.1.4 on 2023-06-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_waitinglist_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airport_destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airport_origin',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='stops',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.provider'),
        ),
    ]
