# Generated by Django 4.1.4 on 2023-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighthistory',
            name='baggage',
            field=models.BooleanField(default=False),
        ),
    ]
