# Generated by Django 4.1.4 on 2023-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.SlugField(max_length=10, null=True, unique=True),
        ),
    ]
