# Generated by Django 4.1.4 on 2023-07-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flighthistory_baggage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flighthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='fare_clean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='tax_miles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='tax_money',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
