# Generated by Django 4.1.4 on 2023-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_remove_airport_region_region_airports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='airports',
            field=models.ManyToManyField(related_name='regions', to='flights.airport'),
        ),
    ]
