# Generated by Django 4.1.4 on 2023-08-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faq_options_faq_sequence_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='sequence',
            field=models.IntegerField(default=9999),
        ),
    ]
