name: Build and push images

on:
  push:
    branches:
      - develop
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client
          build-args: |
            "VITE_MILLEROS_BASE_URL=${{ vars.VITE_MILLEROS_BASE_URL }}"
            "VITE_GOOGLE_ANALYTICS_ID=${{ vars.VITE_GOOGLE_ANALYTICS_ID }}"
          file: ./client/DockerfileProd
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/client:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/client:${{ vars.SUFFIX_IMAGE }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: | 
            ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ vars.SUFFIX_IMAGE }}
