name: Kubernetes Deployment

on:
  push:
    branches:
      - develop  # Change this to the branch you want to trigger deployments from
      - main  # Change this to the branch you want to trigger deployments from

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client
          build-args: |
            "VITE_MILLEROS_BASE_URL=${{ vars.VITE_MILLEROS_BASE_URL_PROD }}"
            "VITE_GOOGLE_ANALYTICS_ID=${{ vars.VITE_GOOGLE_ANALYTICS_ID_PROD }}"
          file: ./client/DockerfileProd
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/client:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/client:stable-latest
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: | 
            ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/server:stable-latest
