name: Deployment

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "${{ env.SERVER_KEY }}" > deploy_key
        chmod 600 deploy_key
        eval $(ssh-agent -s)
        ssh-add deploy_key

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i deploy_key -p ${{ env.SERVER_PORT }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd TrackMiles && git pull && docker compose -f docker-compose.test.yml down -v && docker compose -f docker-compose.test.yml up -d --build --force-recreate && docker compose -f docker-compose.test.yml run server python manage.py migrate && docker compose -f docker-compose.test.yml run server python manage.py populate && docker compose -f docker-compose.test.yml run server python manage.py createsuperuser --no-input"
